// 캐릭터 기본 정보 (운세용)
const CHARS = {
    hakari: {
        name: { ja: '花園羽香里', ko: '하나조노 하카리', en: 'Hakari Hanazono' },
        fortunes: [
            { ja: '今日も愛に溢れた幸せな一日ですね🎵', ko: '오늘도 사랑이 넘치는 행복한 하루네요🎵', en: 'Another day filled with love and happiness🎵' },
            { ja: '完璧な計画が叶いそうな、そんな日...うふふ...😍', ko: '완벽한 계획이 이뤄질 것 같은 그런 날... 음후후...😍', en: 'A day when perfect plans come true... hehe...😍' }
        ]
    },
    karane: {
        name: { ja: '院田唐音', ko: '인다 카라네', en: 'Karane Inda' },
        fortunes: [
            { ja: 'べっ別にいい一日になりそうとか思ってないんだからね！😤', ko: '따, 딱히 좋은 하루일 것 같진 않거든! 😤', en: "I-it's not like it'll be a good day or anything! 😤" },
            { ja: 'こ、幸運を...祈ってあげるわ...🍀', ko: '해, 행운을... 빌어줄게... 🍀', en: "I-I'll wish you good luck... 🍀" }
        ]
    },
    shizuka: {
        name: { ja: '好本静', ko: '요시모토 시즈카', en: 'Shizuka Yoshimoto' },
        fortunes: [
            { ja: '「今日は」「本を読むのに良い」「日です」📘', ko: '"오늘은" 「책을 읽기 좋은」 "날입니다" 📘', en: '"Today is" "a good day" "to read books" 📘' },
            { ja: 'よう！「今日も」ぶっ飛ばしていくぞ！🏃🏻‍♂️🏃🏻‍♀️', ko: '"어이" 「오늘도」 "달려보자고" 🏃🏻‍♂️🏃🏻‍♀️', en: '"Hey!" "Let\'s go" "full speed today too!" 🏃🏻‍♂️🏃🏻‍♀️' }
        ]
    },
    nano: {
        name: { ja: '栄逢凪乃', ko: '에이아이 나노', en: 'Nano Eiai' },
        fortunes: [
            { ja: 'したい事は行動に移したほうが効率的。', ko: '하고 싶은 것이 있을 땐 행동으로 옮기는 편이 효율적.', en: 'Acting on what you want to do is more efficient.' },
            { ja: 'これが「運命の出会い」という概念...🤨', ko: '이것이 「운명의 만남」이라는 개념...🤨', en: 'So this is the concept of "fated encounters"...🤨' }
        ]
    },
    kusuri: {
        name: { ja: '薬膳楠莉', ko: '야쿠젠 쿠스리', en: 'Kusuri Yakuzen' },
        fortunes: [
            { ja: '楽しい一日になるのだ！😆', ko: '즐거운 하루가 될 것이다! 😆', en: 'It will be a fun day, yep, yep! 😆' },
            { ja: '元気になる薬ー！💊', ko: '건강해지는 약-! 💊', en: 'drug that makes you healthy, yep, yep! 💊' }
        ]
    },
    kusuri18: {
        name: { ja: '薬膳楠莉（18歳）', ko: '야쿠젠 쿠스리(18세)', en: 'Kusuri Yakuzen (18)' },
        fortunes: [
            { ja: 'ちょっと大人な一日になりそうなのだよ✨', ko: '조금 어른스러운 하루가 될 것 같다✨', en: 'It seems like it will be a slightly mature day✨' },
            { ja: '新薬の材料をたくさん採取できそうなのだよ', ko: '신약 소재를 듬뿍 채취할 수 있을 것 같은걸', en: 'Looks like I can gather plenty of materials for new drug' }
        ]
    },
    hahari: {
        name: { ja: '花園羽々里', ko: '하나조노 하하리', en: 'Hahari Hanazono' },
        fortunes: [
            { ja: '素敵な時間が待ってるわ❤', ko: '멋진 시간이 기다리고 있어❤', en: 'A wonderful time awaits❤' },
            { ja: 'たまにはこうして甘えてもいいわよ...💗', ko: '가끔은 이렇게 어리광부려도 돼...💗', en: 'It\'s okay to act spoiled like this sometimes...💗' }
        ]
    }
};

// 속성 아이콘
const attributeIcons = {
    red: 'https://i.imgur.com/MOJfYub.png',
    yellow: 'https://i.imgur.com/qv6TUtA.png',
    green: 'https://i.imgur.com/oOZ0svY.png',
    sky: 'https://i.imgur.com/K40J1pK.png',
    purple: 'https://i.imgur.com/dzAAZg2.png'
};

// 캐릭터 데이터 (총 55개)
const characters = [
    // 키스 날리기 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/GnXGPCdbEAAfdpW?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GnXF_1CawAAjekY?format=jpg&name=large', attribute: 'red', theme: { ja: '投げキッス', ko: '키스 날리기', en: 'Blowing Kiss' }, skillName: { ja: 'これからずっとずっと一緒ですね♪', ko: '앞으로도 계속 함께네요♪', en: "We'll be together forever and ever♪" }, skillDesc: { ja: '赤ピースをすべて消します。', ko: '빨강 피스를 전부 제거합니다.', en: 'Clears all red pieces.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/GnXUBBab0AEaIoq?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GncPywbbsAAOTj8?format=jpg&name=large', attribute: 'yellow', theme: { ja: '投げキッス', ko: '키스 날리기', en: 'Blowing Kiss' }, skillName: { ja: 'べっ別に会えて嬉しいなんて思ってないんだからねっ', ko: '따, 딱히 만나서 기쁘다는 생각 같은 건 안 했거든', en: "I-it's not like I'm happy to see you or anything!" }, skillDesc: { ja: '黄色ピースをすべて消します。', ko: '노랑 피스를 전부 제거합니다.', en: 'Clears all yellow pieces.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/Gn67wbSaEAAgc74?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GoAE-s4bMAEQCiE?format=jpg&name=large', attribute: 'sky', theme: { ja: '投げキッス', ko: '키스 날리기', en: 'Blowing Kiss' }, skillName: { ja: '"愛おしい人よ"「今後ともよろしく」"なのです"', ko: '"소중한 그대여" 「앞으로도 잘 부탁드리는」 "바입니다"', en: '"My beloved" "I look forward to our future together" "indeed"' }, skillDesc: { ja: '空色ピースをすべて消します。', ko: '하늘 피스를 전부 제거합니다.', en: 'Clears all sky pieces.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/Gn7JKHYaUAALox7?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GoAS2QCbUAA6_1H?format=jpg&name=large', attribute: 'purple', theme: { ja: '投げキッス', ko: '키스 날리기', en: 'Blowing Kiss' }, skillName: { ja: 'こあなたに呼ばれてここに来た', ko: '네가 불러서 여기에 왔어', en: 'I came here because you called me' }, skillDesc: { ja: '紫ピースをすべて消します。', ko: '보라 피스를 전부 제거합니다.', en: 'Clears all purple pieces.' } },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/Gofg0HFbkAAEaEH?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GokIho4bQAAAZoH?format=jpg&name=large', attribute: 'green', theme: { ja: '投げキッス', ko: '키스 날리기', en: 'Blowing Kiss' }, skillName: { ja: '会えて嬉しいのだー♪', ko: '만나서 반가운 것이다-♪', en: 'I\'m so happy to meet you, yep, yep!♪' }, skillDesc: { ja: '緑ピースをすべて消します。', ko: '초록 피스를 전부 제거합니다.', en: 'Clears all green pieces.' } },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/GofntvlaEAALPFH?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GokV9OibAAAimte?format=jpg&name=large', attribute: 'green', theme: { ja: '投げキッス', ko: '키스 날리기', en: 'Blowing Kiss' }, skillName: { ja: 'おや？なぜ顔を赤くしているのだね？', ko: '응? 어째서 얼굴이 빨개진 거야?', en: 'Oh? Why is your face turning red?' }, skillDesc: { ja: '緑ピースをすべて消します。', ko: '초록 피스를 전부 제거합니다.', en: 'Clears all green pieces.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/GofujyyaIAAsxkW?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gokjy8HbwAA8X3o?format=jpg&name=large', attribute: 'red', theme: { ja: '投げキッス', ko: '키스 날리기', en: 'Blowing Kiss' }, skillName: { ja: 'あなたとの出会いは運命かしらね♡', ko: '당신과의 만남은 운명일지도♡', en: 'Meeting you might be destiny, don\'t you think?♡' }, skillDesc: { ja: '赤ピースをすべて消します。', ko: '빨강 피스를 전부 제거합니다.', en: 'Clears all red pieces.' } },
    
    // 토끼귀 패밀리 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/GpYDrWuacAAMl5E?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GpWxFeWbkAALrYv?format=jpg&name=large', attribute: 'purple', theme: { ja: 'うさ耳ファミリー', ko: '토끼귀 패밀리', en: 'Bunny Ear Family' }, skillName: { ja: 'ぴょんぴょん♪うさぎさんですよ～', ko: '깡총깡총♪ 토끼 씨예요~', en: 'Hop hop♪ I\'m a bunny~' }, skillDesc: { ja: '自分を中心として5x5のピースを消します。', ko: '자신을 중심으로 5x5 피스를 지웁니다.', en: 'Clears 5x5 pieces centered on self.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/Go4uj9abQAA_bOM?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GozlGT5bgAA6lj9?format=jpg&name=large', attribute: 'red', theme: { ja: 'うさ耳ファミリー', ko: '토끼귀 패밀리', en: 'Bunny Ear Family' }, skillName: { ja: 'な、なに見てるのよっ！', ko: '뭐, 뭘 보는 거야!', en: 'Wh-what are you looking at!' }, skillDesc: { ja: '自分を中心として5x5のピースを消します。', ko: '자신을 중심으로 5x5 피스를 지웁니다.', en: 'Clears 5x5 pieces centered on self.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/Go48Mm8a4AAA9G9?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gozrv1EbgAAAWaU?format=jpg&name=large', attribute: 'yellow', theme: { ja: 'うさ耳ファミリー', ko: '토끼귀 패밀리', en: 'Bunny Ear Family' }, skillName: { ja: '"未知なる世界"「への」"扉を開いたのだ"', ko: '"미지의 세계" 「로 향하는」 "문을 연 것이다"', en: '"Opened the door" "to" "an unknown world"' }, skillDesc: { ja: '自分を中心として5x5のピースを消します。', ko: '자신을 중심으로 5x5 피스를 지웁니다.', en: 'Clears 5x5 pieces centered on self.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/Go5KCU7aYAAviB1?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GozytqZasAAvTGQ?format=jpg&name=large', attribute: 'sky', theme: { ja: 'うさ耳ファミリー', ko: '토끼귀 패밀리', en: 'Bunny Ear Family' }, skillName: { ja: '大きな耳は音を聴くのに効率的', ko: '큰 귀는 소리를 듣는 데 효율적', en: 'Big ears are efficient for hearing sounds' }, skillDesc: { ja: '自分を中心として5x5のピースを消します。', ko: '자신을 중심으로 5x5 피스를 지웁니다.', en: 'Clears 5x5 pieces centered on self.' } },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/Go5XtRpasAAgd13?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Goz5fLRa0AAAeJG?format=jpg&name=large', attribute: 'purple', theme: { ja: 'うさ耳ファミリー', ko: '토끼귀 패밀리', en: 'Bunny Ear Family' }, skillName: { ja: 'おぉ～耳が4つになったのだ！', ko: '오오~ 귀가 4개가 된 것이다!', en: 'Ooh~ I have four ears now, yep, yep!' }, skillDesc: { ja: '自分を中心として5x5のピースを消します。', ko: '자신을 중심으로 5x5 피스를 지웁니다.', en: 'Clears 5x5 pieces centered on self.' } },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/GpXol5bbYAEJh5I?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GpWWqVYbsAA2Md4?format=jpg&name=large', attribute: 'yellow', theme: { ja: 'うさ耳ファミリー', ko: '토끼귀 패밀리', en: 'Bunny Ear Family' }, skillName: { ja: 'ふむ、うさぎになりきるのも悪くないのだよ', ko: '흠, 토끼가 되는 것도 나쁘지 않은 것이야', en: 'Hmm, becoming a bunny isn\'t so bad' }, skillDesc: { ja: '自分を中心として5x5のピースを消します。', ko: '자신을 중심으로 5x5 피스를 지웁니다.', en: 'Clears 5x5 pieces centered on self.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/GpX2IcWacAArzqR?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GpWjeE8bYAIcTQ3?format=jpg&name=large', attribute: 'green', theme: { ja: 'うさ耳ファミリー', ko: '토끼귀 패밀리', en: 'Bunny Ear Family' }, skillName: { ja: 'ぴょんぴょん♪…ってこんなところ羽香里に見られたら…', ko: '깡총깡총♪ ...근데 이런 모습을 하카리에게 들키면...', en: 'Hop hop♪… if Hakari saw me like this…' }, skillDesc: { ja: '自分を中心として5x5のピースを消します。', ko: '자신을 중심으로 5x5 피스를 지웁니다.', en: 'Clears 5x5 pieces centered on self.' } },
    
    // 치어리더즈 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/GryH1B8XEAEvCCI?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Grw1arLWgAAKqki?format=jpg&name=large', attribute: 'yellow', theme: { ja: 'チアリーダーズ', ko: '치어리더즈', en: 'Cheerleaders' }, skillName: { ja: 'フレ～♪フレ～♪声援、送っちゃいますよ～', ko: '플레이~♪ 플레이~♪ 열심히 응원할게요~', en: 'Cheer~♪ Cheer~♪ I\'ll cheer you on~' }, skillDesc: { ja: '自分を中心して丸型にピースを消します。\n2ターンの間、2コンボ以上のコンボ倍率が2倍に変化します。', ko: '자신을 중심으로 원형으로 피스를 제거합니다.\n2턴 동안 2콤보 이상 콤보 배율이 2배가 됩니다.', en: 'Clears pieces in a circle centered on self.\nFor 2 turns, combo multiplier for 2+ combos becomes 2x.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/GryVeyYWQAAxB2p?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GrxDBh6WwAAGXR4?format=jpg&name=large', attribute: 'green', theme: { ja: 'チアリーダーズ', ko: '치어리더즈', en: 'Cheerleaders' }, skillName: { ja: '別にあんたのために応援してあげてるわけじゃないんだからね！', ko: '딱히 널 위해서 응원하는 게 아니거든!', en: 'It\'s not like I\'m cheering for you or anything!' }, skillDesc: { ja: '自分を中心して丸型にピースを消します。\n2ターンの間、2コンボ以上のコンボ倍率が2倍に変化します。', ko: '자신을 중심으로 원형으로 피스를 제거합니다.\n2턴 동안 2콤보 이상 콤보 배율이 2배가 됩니다.', en: 'Clears pieces in a circle centered on self.\nFor 2 turns, combo multiplier for 2+ combos becomes 2x.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/Gp29IbibwAAusLS?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gp2T5u3agAA3yrx?format=jpg&name=large', attribute: 'purple', theme: { ja: 'チアリーダーズ', ko: '치어리더즈', en: 'Cheerleaders' }, skillName: { ja: '"気高き闘士たちよ"「いざ行かん」', ko: '"고귀한 전사들이여" 「자 나아가자」', en: '"Noble fighters" "Let us go forth"' }, skillDesc: { ja: '自分を中心して丸型にピースを消します。\n2ターンの間、2コンボ以上のコンボ倍率が2倍に変化します。', ko: '자신을 중심으로 원형으로 피스를 제거합니다.\n2턴 동안 2콤보 이상 콤보 배율이 2배가 됩니다.', en: 'Clears pieces in a circle centered on self.\nFor 2 turns, combo multiplier for 2+ combos becomes 2x.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/Gp22HdNa8AAYE2y?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gp2M-MTaYAEm9xn?format=jpg&name=large', attribute: 'green', theme: { ja: 'チアリーダーズ', ko: '치어리더즈', en: 'Cheerleaders' }, skillName: { ja: '応援の気持ちを伝えるのに効率的な衣装', ko: '응원하는 마음을 전하는 데 효율적인 의상', en: 'Outfit efficient for conveying supportive feelings' }, skillDesc: { ja: '自分を中心して丸型にピースを消します。\n2ターンの間、2コンボ以上のコンボ倍率が2倍に変化します。', ko: '자신을 중심으로 원형으로 피스를 제거합니다.\n2턴 동안 2콤보 이상 콤보 배율이 2배가 됩니다.', en: 'Clears pieces in a circle centered on self.\nFor 2 turns, combo multiplier for 2+ combos becomes 2x.' } },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/Gqk4ASibcAABCtw?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gqjlvc8bcAAhs9O?format=jpg&name=large', attribute: 'red', theme: { ja: 'チアリーダーズ', ko: '치어리더즈', en: 'Cheerleaders' }, skillName: { ja: 'フレーフレー！頑張れなのだ！', ko: '플레이- 플레이-! 힘내라는 것이다!', en: 'Cheer! Cheer! Do your best, yep, yep!' }, skillDesc: { ja: '自分を中心して丸型にピースを消します。\n2ターンの間、2コンボ以上のコンボ倍率が2倍に変化します。', ko: '자신을 중심으로 원형으로 피스를 제거합니다.\n2턴 동안 2콤보 이상 콤보 배율이 2배가 됩니다.', en: 'Clears pieces in a circle centered on self.\nFor 2 turns, combo multiplier for 2+ combos becomes 2x.' } },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/Gq-1jJiaAAETICm?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gq9jLRCaAAAF4ee?format=jpg&name=large', attribute: 'sky', theme: { ja: 'チアリーダーズ', ko: '치어리더즈', en: 'Cheerleaders' }, skillName: { ja: 'さぁ、頑張るのだよ', ko: '자, 힘내는 거야', en: 'Now, do your best' }, skillDesc: { ja: '自分を中心して丸型にピースを消します。\n2ターンの間、2コンボ以上のコンボ倍率が2倍に変化します。', ko: '자신을 중심으로 원형으로 피스를 제거합니다.\n2턴 동안 2콤보 이상 콤보 배율이 2배가 됩니다.', en: 'Clears pieces in a circle centered on self.\nFor 2 turns, combo multiplier for 2+ combos becomes 2x.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/Gq-n0xgaAAIEzNe?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gq9WIUBaAAA6rNQ?format=jpg&name=large', attribute: 'purple', theme: { ja: 'チアリーダーズ', ko: '치어리더즈', en: 'Cheerleaders' }, skillName: { ja: 'フレー♪フレー♪が・ん・ば・れ♡', ko: '플레이~♪ 플레이~♪ 파·이·팅♡', en: 'Cheer♪ Cheer♪ F·i·g·h·t♡' }, skillDesc: { ja: '自分を中心して丸型にピースを消します。\n2ターンの間、2コンボ以上のコンボ倍率が2倍に変化します。', ko: '자신을 중심으로 원형으로 피스를 제거합니다.\n2턴 동안 2콤보 이상 콤보 배율이 2배가 됩니다.', en: 'Clears pieces in a circle centered on self.\nFor 2 turns, combo multiplier for 2+ combos becomes 2x.' } },
    
    // 꿈의 드레스 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/GtjosTibsAEx8l2?format=jpg&name=large', detailImage: 'https://i.imgur.com/UoIsHA7.png', attribute: 'sky', theme: { ja: '憧れのドレス', ko: '꿈의 드레스', en: 'Dream Dress' }, skillName: { ja: 'ふつつかものですが……みんなで幸せになりましょう', ko: '부족한 사람이지만...... 함께 행복해져요', en: 'I may be inadequate but...... let\'s all be happy together' }, skillDesc: { ja: '自分を中心してクリスタル型にピースを消します。', ko: '자신을 중심으로 크리스탈 모양으로 피스를 제거합니다.', en: 'Clears pieces in a crystal shape centered on self.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/GuRxzN5aUAAiIOV?format=jpg&name=large', detailImage: 'https://i.imgur.com/FO8DFli.png', attribute: 'green', theme: { ja: '憧れのドレス', ko: '꿈의 드레스', en: 'Dream Dress' }, skillName: { ja: 'べ、別に憧れてるわけじゃないんだからね！', ko: '따, 딱히 동경하는 건 아니거든!', en: 'I-it\'s not like I admire it or anything!' }, skillDesc: { ja: '自分を中心してクリスタル型にピースを消します。', ko: '자신을 중심으로 크리스탈 모양으로 피스를 제거합니다.', en: 'Clears pieces in a crystal shape centered on self.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/GsbUvyoakAAEp5m?format=jpg&name=large', detailImage: 'https://i.imgur.com/LaIHUQs.png', attribute: 'red', theme: { ja: '憧れのドレス', ko: '꿈의 드레스', en: 'Dream Dress' }, skillName: { ja: '"縁定めの契りを"「そなたと交わしたい」', ko: '"인연을 맺는 맹세를" 「그대와 나누고 싶다」', en: '"I wish to make" "a vow of fate with thee."' }, skillDesc: { ja: '自分を中心してクリスタル型にピースを消します。', ko: '자신을 중심으로 크리스탈 모양으로 피스를 제거합니다.', en: 'Clears pieces in a crystal shape centered on self.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/GuR-3zTbMAAaaTy?format=jpg&name=large', detailImage: 'https://i.imgur.com/NPgoXYj.png', attribute: 'yellow', theme: { ja: '憧れのドレス', ko: '꿈의 드레스', en: 'Dream Dress' }, skillName: { ja: '…素敵、あなたと出会わなければそう思うこともなかった', ko: '...굉장해, 너를 만나지 않았다면 이런 생각은 하지도 못 했을 거야', en: '...Wonderful, I would never have thought this if I hadn\'t met you' }, skillDesc: { ja: '自分を中心してクリスタル型にピースを消します。', ko: '자신을 중심으로 크리스탈 모양으로 피스를 제거합니다.', en: 'Clears pieces in a crystal shape centered on self.' } },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/GsbiJU7aoAAbkap?format=jpg&name=large', detailImage: 'https://i.imgur.com/fFfypOF.png', attribute: 'green', theme: { ja: '憧れのドレス', ko: '꿈의 드레스', en: 'Dream Dress' }, skillName: { ja: 'お花のドレス着れたのだ！写真撮りまくるのだー！', ko: '꽃 드레스를 입은 것이다! 사진을 잔뜩 찍는 것이다-!', en: 'I got to wear a flower dress, yep, yep!\nI\'ll take tons of photos, yep, yep!' }, skillDesc: { ja: '自分を中心してクリスタル型にピースを消します。', ko: '자신을 중심으로 크리스탈 모양으로 피스를 제거합니다.', en: 'Clears pieces in a crystal shape centered on self.' } },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/Gs_X6k3bIAAsvqy?format=jpg&name=large', detailImage: 'https://i.imgur.com/i4EBmuw.png', attribute: 'purple', theme: { ja: '憧れのドレス', ko: '꿈의 드레스', en: 'Dream Dress' }, skillName: { ja: 'おや、なぜ顔を赤くして楠莉を見つめるのだね？', ko: '응? 어째서 얼굴이 빨개져서 쿠스리를 바라보는 거야?', en: 'Oh, why are you blushing and staring at Kusuri?' }, skillDesc: { ja: '自分を中心してクリスタル型にピースを消します。', ko: '자신을 중심으로 크리스탈 모양으로 피스를 제거합니다.', en: 'Clears pieces in a crystal shape centered on self.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/GtjawWYaMAAiM63?format=jpg&name=large', detailImage: 'https://i.imgur.com/iLAohAB.png', attribute: 'yellow', theme: { ja: '憧れのドレス', ko: '꿈의 드레스', en: 'Dream Dress' }, skillName: { ja: 'わ、私がウェディングドレスを着れるなんて…ありがとう…', ko: '내, 내가 웨딩 드레스를 입게 될 줄은... 고마워...', en: 'I-I can\'t believe I get to wear a wedding dress... Thank you...' }, skillDesc: { ja: '自分を中心してクリスタル型にピースを消します。', ko: '자신을 중심으로 크리스탈 모양으로 피스를 제거합니다.', en: 'Clears pieces in a crystal shape centered on self.' } },
    
    // 칠석 축제 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/Gu10p0paEAATq9F?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Guvl3QAaIAANyRO?format=jpg&name=large', attribute: 'green', theme: { ja: '星祭り', ko: '칠석 축제', en: 'Star Festival' }, skillName: { ja: 'どんなに遠く離れたとしても…すぐに会いに来てくれますよね♪', ko: '아무리 멀리 떨어지게 되더라도… 곧바로 만나러 와주실 거죠♪', en: 'No matter how far apart we are…\nyou\'ll come see me right away, right?♪' }, skillDesc: { ja: '自分を中心して斜めライン状にピースを消します。', ko: '자신을 중심으로 대각선 모양으로 피스를 제거합니다.', en: 'Clears pieces diagonally centered on self.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/GwDD9PeaMAA9gDD?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gv8o5OEa4AALsAF?format=jpg&name=large', attribute: 'sky', theme: { ja: '星祭り', ko: '칠석 축제', en: 'Star Festival' }, skillName: { ja: 'いつまでも待ってられるに決まってんじゃない…', ko: '언제까지든 기다릴 수 있는 게 당연하잖아...', en: 'Of course I can wait forever...' }, skillDesc: { ja: '自分を中心して斜めライン状にピースを消します。', ko: '자신을 중심으로 대각선 모양으로 피스를 제거합니다.', en: 'Clears pieces diagonally centered on self.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/Gwxan3wa4AAvxZW?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gwq_TcVbgAABjpw?format=jpg&name=large', attribute: 'purple', theme: { ja: '星祭り', ko: '칠석 축제', en: 'Star Festival' }, skillName: { ja: '"長き時の隔たり"「今こそ超える時」', ko: '"오랜 세월의 간극" 「지금이야말로 뛰어넘을 때」', en: '"The long gap of time" "Now is the time to overcome"' }, skillDesc: { ja: '自分を中心して斜めライン状にピースを消します。', ko: '자신을 중심으로 대각선 모양으로 피스를 제거합니다.', en: 'Clears pieces diagonally centered on self.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/GvZ3bn2agAAF7fC?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GvYlnVqaUAAbqVU?format=jpg&name=large', attribute: 'red', theme: { ja: '星祭り', ko: '칠석 축제', en: 'Star Festival' }, skillName: { ja: '1年に1度しか会えないなんて非効率的…でも会いに来た', ko: '1년에 1번밖에 못 만난다니 비효율적... 그래도 만나러 왔어', en: 'Only meeting once a year is inefficient... but I came to see you' }, skillDesc: { ja: '自分を中心して斜めライン状にピースを消します。', ko: '자신을 중심으로 대각선 모양으로 피스를 제거합니다.', en: 'Clears pieces diagonally centered on self.' } },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/GwDRuu1bQAA3Nqh?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Gv81rtBa4AI21eV?format=jpg&name=large', attribute: 'yellow', theme: { ja: '星祭り', ko: '칠석 축제', en: 'Star Festival' }, skillName: { ja: '彦星はどこにいるのだ？早く会いてーのだ', ko: '견우는 어디 있는 것이다? 얼른 만나고 싶은 것이다', en: 'Where is Hikoboshi, yep, yep? I want to meet him soon, yep, yep' }, skillDesc: { ja: '自分を中心して斜めライン状にピースを消します。', ko: '자신을 중심으로 대각선 모양으로 피스를 제거합니다.', en: 'Clears pieces diagonally centered on self.' } },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/Gu2CEqCbAAAEhG6?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/Guvzkc3a4AA499W?format=jpg&name=large', attribute: 'red', theme: { ja: '星祭り', ko: '칠석 축제', en: 'Star Festival' }, skillName: { ja: '薬の力でいつでも会いに行けるようになればいいんだがな…', ko: '약의 힘으로 언제든지 만나러 갈 수 있으면 좋을 텐데...', en: 'I wish I could go see you anytime with the help of drug...' }, skillDesc: { ja: '自分を中心して斜めライン状にピースを消します。', ko: '자신을 중심으로 대각선 모양으로 피스를 제거합니다.', en: 'Clears pieces diagonally centered on self.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/GwxoE3CaMAA1Qsg?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GwrMD1ZbgAIwO2i?format=jpg&name=large', attribute: 'sky', theme: { ja: '星祭り', ko: '칠석 축제', en: 'Star Festival' }, skillName: { ja: '私の彦星様はどこにいるのかしら～♡', ko: '내 견우님은 어디 있는 걸까~♡', en: 'Where is my Hikoboshi~♡' }, skillDesc: { ja: '自分を中心して斜めライン状にピースを消します。', ko: '자신을 중심으로 대각선 모양으로 피스를 제거합니다.', en: 'Clears pieces diagonally centered on self.' } },
    
    // 마린 서머 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/G6z3LqBbwAAb3Uc?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G6wUBvna0Acfq5u?format=jpg&name=large', attribute: 'sky', theme: { ja: 'マリンサマー', ko: '마린 서머', en: 'Marine Summer' }, skillName: { ja: 'キャッ!? つめた～い♪ もう…私も！えい、え～い♪ うふふ', ko: '꺅!? 차가워~♪ 에잇... 저도! 에잇, 에~잇♪ 우후후', en: 'Kyaa!? So cold~♪ Geez... Me too! Take this~♪ Ehehe' }, skillDesc: { ja: '自分を中心して浮き輪型にピースを消します。', ko: '자신을 중심으로 튜브 모양으로 피스를 제거합니다.', en: 'Clears pieces in a floaties shape centered on self.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/GxPqoqmaIAIE8X9?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GxKTTxNaIAAImb4?format=jpg&name=large', attribute: 'yellow', theme: { ja: 'マリンサマー', ko: '마린 서머', en: 'Marine Summer' }, skillName: { ja: '…あ…あんたのほうが……してるし…ドキドキ…', ko: '너...너가 더... 그러고 있잖아... 두근두근...', en: 'Y-you\'re the one... whose heart is... pounding...' }, skillDesc: { ja: '自分を中心して浮き輪型にピースを消します。', ko: '자신을 중심으로 튜브 모양으로 피스를 제거합니다.', en: 'Clears pieces in a floaties shape centered on self.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/Gx4po_Wb0AANjHs?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GxzF6hmbsAANm-t?format=jpg&name=large', attribute: 'green', theme: { ja: 'マリンサマー', ko: '마린 서머', en: 'Marine Summer' }, skillName: { ja: '"これが"「水中戦での」"我が戦闘服"「である」', ko: '"이것이" 「수중전에 입는」 "나의 전투복" 「이다」', en: '"This is" "my battle outfit" "for water combat"' }, skillDesc: { ja: '自分を中心して浮き輪型にピースを消します。', ko: '자신을 중심으로 튜브 모양으로 피스를 제거합니다.', en: 'Clears pieces in a floaties shape centered on self.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/GxPdF9baIAIIyqS?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GxKFl9kbAAAW3WI?format=jpg&name=large', attribute: 'purple', theme: { ja: 'マリンサマー', ko: '마린 서머', en: 'Marine Summer' }, skillName: { ja: '女性的な魅力を感じてもらうのにとても効率的', ko: '여성적인 매력을 느끼게 하는데 매우 효율적', en: 'Very efficient for conveying feminine charm' }, skillDesc: { ja: '自分を中心して浮き輪型にピースを消します。', ko: '자신을 중심으로 튜브 모양으로 피스를 제거합니다.', en: 'Clears pieces in a floaties shape centered on self.' } },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/GxP4h3racAABtyL?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GxKhOtjbsAARye7?format=jpg&name=large', attribute: 'sky', theme: { ja: 'マリンサマー', ko: '마린 서머', en: 'Marine Summer' }, skillName: { ja: 'たくさん泳ぐのだー！水の滑り台も行きてーのだ！', ko: '잔뜩 수영하는 것이다-! 워터 슬라이드도 타고 싶은 것이다!', en: 'I\'ll swim a lot, yep, yep!\nI wanna ride the water slide too, yep, yep!' }, skillDesc: { ja: '自分を中心して浮き輪型にピースを消します。', ko: '자신을 중심으로 튜브 모양으로 피스를 제거합니다.', en: 'Clears pieces in a floaties shape centered on self.' } },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/Gx43hQybsAEiiWt?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/GxzSYawaAAAaEnC?format=jpg&name=large', attribute: 'purple', theme: { ja: 'マリンサマー', ko: '마린 서머', en: 'Marine Summer' }, skillName: { ja: '普段の姿とはまた違う魅力があるだろう？', ko: '평소 모습과는 또 다른 매력이 있지?', en: 'It has a different charm from usual, doesn\'t it?' }, skillDesc: { ja: '自分を中心して浮き輪型にピースを消します。', ko: '자신을 중심으로 튜브 모양으로 피스를 제거합니다.', en: 'Clears pieces in a floaties shape centered on self.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/G60EhWqbEAA4pdy?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G6wbOjla0AA7atc?format=jpg&name=large', attribute: 'red', theme: { ja: 'マリンサマー', ko: '마린 서머', en: 'Marine Summer' }, skillName: { ja: 'あら♡かわいい水着姿ね♡さ、早く遊びに行きましょ♡', ko: '어머♡ 귀여운 수영복이네♡ 자, 얼른 놀러가자♡', en: 'Oh my♡ What a cute swimsuit♡ Now, let\'s go have fun♡' }, skillDesc: { ja: '自分を中心して浮き輪型にピースを消します。', ko: '자신을 중심으로 튜브 모양으로 피스를 제거합니다.', en: 'Clears pieces in a floaties shape centered on self.' } },

    // 꿈처럼 귀여운 밤 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/G4g3iskbQAAdpmx?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G4gVPbJa8AkZ458?format=jpg&name=large', attribute: 'purple', theme: { ja: 'ゆめかわナイト', ko: '꿈처럼 귀여운 밤', en: 'Yumekawa Night' }, skillName: { ja: '私にイタズラしてもいいんですよ♪…ぜひしてください！', ko: '저에게 장난쳐도 된다구요♪ ...꼭 해 주세요!', en: 'You can play tricks on me, you know♪ ...Please do it!' }, skillDesc: { ja: '赤ピースをランダムに5つ紫ピースに変換します。\n自分を中心としてキャンディー型にピースを消します。', ko: '무작위 빨강 피스 5개를 보라 피스로 바꿉니다.\n자기 중심으로 캔디 모양으로 피스를 제거합니다.', en: 'Randomly changes 5 red pieces to purple pieces.\nClears pieces in a candy shape centered on self.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/G4g-Zrwa8AEN3aY?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G4gcSjSa8Ak88Fv?format=jpg&name=large', attribute: 'red', theme: { ja: 'ゆめかわナイト', ko: '꿈처럼 귀여운 밤', en: 'Yumekawa Night' }, skillName: { ja: 'ふんッ！いたずらでもなんでもやればいいでしょ、やればっ！', ko: '흥! 장난이든 뭐든 하면 되잖아, 하면!', en: 'Hmph! Fine, I\'ll just do it—whether it\'s a prank or whatever, I\'ll do it!' }, skillDesc: { ja: '緑ピースをランダムに5つ赤ピースに変換します。\n自分を中心としてキャンディー型にピースを消します。', ko: '무작위 초록 피스 5개를 빨강 피스로 바꿉니다.\n자기 중심으로 캔디 모양으로 피스를 제거합니다.', en: 'Randomly changes 5 green pieces to red pieces.\nClears pieces in a candy shape centered on self.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/G5DoYnsaYAA_61x?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G5CxbpNaAAAChxa?format=jpg&name=large', attribute: 'yellow', theme: { ja: 'ゆめかわナイト', ko: '꿈처럼 귀여운 밤', en: 'Yumekawa Night' }, skillName: { ja: '"甘美なる誘惑を求め"「共に歩もう」', ko: '"달콤한 유혹을 찾아" 「함께 나아가자」', en: '"Let us walk together" "in search of sweet temptation"' }, skillDesc: { ja: '紫ピースをランダムに5つ黄色ピースに変換します。\n自分を中心としてキャンディー型にピースを消します。', ko: '무작위 보라 피스 5개를 노랑 피스로 바꿉니다.\n자기 중심으로 캔디 모양으로 피스를 제거합니다.', en: 'Randomly changes 5 purple pieces to yellow pieces.\nClears pieces in a candy shape centered on self.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/G5Dalfca0AAvSE-?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G5CkrNEbQAAa3Cg?format=jpg&name=large', attribute: 'sky', theme: { ja: 'ゆめかわナイト', ko: '꿈처럼 귀여운 밤', en: 'Yumekawa Night' }, skillName: { ja: 'お菓子はなくていい…いたずらはさせてもらう', ko: '과자는 없어도 돼... 장난은 치도록 할게', en: 'I don\'t need any treats… but I’m definitely playing a prank.' }, skillDesc: { ja: '黄色ピースをランダムに5つ空色ピースに変換します。\n自分を中心としてキャンディー型にピースを消します。', ko: '무작위 노랑 피스 5개를 하늘 피스로 바꿉니다.\n자기 중심으로 캔디 모양으로 피스를 제거합니다.', en: 'Randomly changes 5 yellow pieces to sky pieces.\nClears pieces in a candy shape centered on self.' } },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/G4hFWq_aAAAwKYx?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G4gi93fa8AQBRW9?format=jpg&name=large', attribute: 'red', theme: { ja: 'ゆめかわナイト', ko: '꿈처럼 귀여운 밤', en: 'Yumekawa Night' }, skillName: { ja: 'お菓子をくれなきゃ薬をかけちゃうのだ～♪', ko: '과자를 주지 않으면 약을 뿌리는 것이다~♪', en: 'Give me a treat, or I\'ll spray you with my drug~♪' }, skillDesc: { ja: '緑ピースをランダムに5つ赤ピースに変換します。\n自分を中心としてキャンディー型にピースを消します。', ko: '무작위 초록 피스 5개를 빨강 피스로 바꿉니다.\n자기 중심으로 캔디 모양으로 피스를 제거합니다.', en: 'Randomly changes 5 green pieces to red pieces.\nClears pieces in a candy shape centered on self.' } },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/G5D2Xa0bIAQ9Tse?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G5C_HWhbIAUnwz8?format=jpg&name=large', attribute: 'sky', theme: { ja: 'ゆめかわナイト', ko: '꿈처럼 귀여운 밤', en: 'Yumekawa Night' }, skillName: { ja: '楠莉はお菓子よりも実験という名のいたずらを所望するのだが……', ko: '쿠스리는 과자보다도 실험이라는 이름의 장난을 원한다만......', en: 'Kusuri craves mischief in the name of experimentation\nmore than sweets...' }, skillDesc: { ja: '黄色ピースをランダムに5つ空色ピースに変換します。\n自分を中心としてキャンディー型にピースを消します。', ko: '무작위 노랑 피스 5개를 하늘 피스로 바꿉니다.\n자기 중심으로 캔디 모양으로 피스를 제거합니다.', en: 'Randomly changes 5 yellow pieces to sky pieces.\nClears pieces in a candy shape centered on self.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/G5EEGlLbQAAkvlM?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G5DNBWnaYAANAqu?format=jpg&name=large', attribute: 'green', theme: { ja: 'ゆめかわナイト', ko: '꿈처럼 귀여운 밤', en: 'Yumekawa Night' }, skillName: { ja: 'お菓子くれてもぉ～ イタズラしちゃうわ～♡', ko: '과자를 준다 해도~ 장난쳐버릴거야~♡', en: 'Even if you give me a treat~ I\'m still gonna play a prank~♡' }, skillDesc: { ja: '空色ピースをランダムに5つ緑ピースに変換します。\n自分を中心としてキャンディー型にピースを消します。', ko: '무작위 하늘 피스 5개를 초록 피스로 바꿉니다.\n자기 중심으로 캔디 모양으로 피스를 제거합니다.', en: 'Randomly changes 5 sky pieces to green pieces.\nClears pieces in a candy shape centered on self.' } },

    // 이상한 나라 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/G6RGcgGaYAAz3mv?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G6KqGCqasAAYHPp?format=jpg&name=large', attribute: 'red', theme: { ja: '不思議の国', ko: '이상한 나라', en: 'Wonderland' }, skillName: { ja: 'どうして私が悪役なんですか⁈ もう～っ!!', ko: '어째서 제가 악역인가요?! 정말~!!', en: 'Why am I the villain?! Geez!!' }, skillDesc: { ja: '自分を中心として1マスずつ空けた7x7のピースを消します。', ko: '자신을 중심으로 1칸을 띄우고 7x7 피스를 제거합니다.', en: 'Clears pieces in a 7x7 area around yourself, with every other space empty.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/G5rxgeuasAAXmC6?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G5oUzUlacAQFQji?format=jpg&name=large', attribute: 'purple', theme: { ja: '不思議の国', ko: '이상한 나라', en: 'Wonderland' }, skillName: { ja: 'な、なんで私がうさぎなのよ え…似合ってる…？…ありがと', ko: '왜, 왜 내가 토끼인 거야. 어.. 어울려..? ...고마워', en: 'W-why am I a rabbit? Oh... it suits me...? ...Thanks.' }, skillDesc: { ja: '自分を中心として1マスずつ空けた7x7のピースを消します。', ko: '자신을 중심으로 1칸을 띄우고 7x7 피스를 제거합니다.', en: 'Clears pieces in a 7x7 area around yourself, with every other space empty.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/G6RhVg6asAEF1md?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G6LFcfracAAu9Yn?format=jpg&name=large', attribute: 'sky', theme: { ja: '不思議の国', ko: '이상한 나라', en: 'Wonderland' }, skillName: { ja: '"よう！お前らも俺と"「ティーパーティー」"しねぇか"', ko: '"여어! 니들도 나랑" 「티 파티」 "나 하자고"', en: '"Yo!" "Why don\'t you guys join me for" "a tea party?"' }, skillDesc: { ja: '自分を中心として1マスずつ空けた7x7のピースを消します。', ko: '자신을 중심으로 1칸을 띄우고 7x7 피스를 제거합니다.', en: 'Clears pieces in a 7x7 area around yourself, with every other space empty.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/G5r-MDaa8AAX-3n?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G5obes0aMAA6pmz?format=jpg&name=large', attribute: 'yellow', theme: { ja: '不思議の国', ko: '이상한 나라', en: 'Wonderland' }, skillName: { ja: 'お茶会をしている暇はない 少しでも早く先に進むべき', ko: '다과회를 할 여유는 없어. 조금이라도 빨리 앞으로 가야 해', en: 'No time for tea parties.\nWe should move forward as quickly as possible.' }, skillDesc: { ja: '自分を中心として1マスずつ空けた7x7のピースを消します。', ko: '자신을 중심으로 1칸을 띄우고 7x7 피스를 제거합니다.', en: 'Clears pieces in a 7x7 area around yourself, with every other space empty.'} },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/G6RT9M5aYAASyw0?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G6K30Z5bkAAw8F5?format=jpg&name=large', attribute: 'purple', theme: { ja: '不思議の国', ko: '이상한 나라', en: 'Wonderland' }, skillName: { ja: 'このしましまのネコ消えるのだ！薬が無くても消えるのだ！', ko: '이 줄무늬 고양이는 사라지는 것이다! 약이 없는데도 사라지는 것이다!', en: 'This striped cat disappears, yep, yep!\nIt vanishes even without a drug, yep yep!' }, skillDesc: { ja: '自分を中心として1マスずつ空けた7x7のピースを消します。', ko: '자신을 중심으로 1칸을 띄우고 7x7 피스를 제거합니다.', en: 'Clears pieces in a 7x7 area around yourself, with every other space empty.' } },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/G5sMENnacAA4CS1?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G5oiX5cacAYlM_x?format=jpg&name=large', attribute: 'green', theme: { ja: '不思議の国', ko: '이상한 나라', en: 'Wonderland' }, skillName: { ja: 'ほう、このネコは薬が無くても姿を消せるのか…', ko: '호오. 이 고양이는 약이 없어도 모습을 감출 수 있는 건가...', en: 'Ho, so this cat can vanish even without drug...' }, skillDesc: { ja: '自分を中心として1マスずつ空けた7x7のピースを消します。', ko: '자신을 중심으로 1칸을 띄우고 7x7 피스를 제거합니다.', en: 'Clears pieces in a 7x7 area around yourself, with every other space empty.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/G6RvPxQbEAA02b7?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G6LTJEXacAI_r9M?format=jpg&name=large', attribute: 'yellow', theme: { ja: '不思議の国', ko: '이상한 나라', en: 'Wonderland' }, skillName: { ja: 'うさぎに帽子屋にチェシャ猫に女王に…み～んな可愛いわぁぁ゛っ', ko: '토끼에 모자 장수에 체셔 고양이에 여왕에... 다~들 귀여워어엇', en: 'Rabbits, hatters, Cheshire cats, queens... they\'re all so cuuuute!' }, skillDesc: { ja: '自分を中心として1マスずつ空けた7x7のピースを消します。', ko: '자신을 중심으로 1칸을 띄우고 7x7 피스를 제거합니다.', en: 'Clears pieces in a 7x7 area around yourself, with every other space empty.' } },

    // 사랑에 빠진 산타 (7)
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/G7yFIaRaMAI6y-w?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G7yFIaRaMAI6y-w?format=jpg&name=large', attribute: 'green', theme: { ja: '恋するサンタ', ko: '사랑에 빠진 산타', en: 'Santa in Love' }, skillName: { ja: 'メリークリスマス♪ プレゼントは…わたしです♪', ko: '메리 크리스마스♪ 선물은... 저예요♪', en: 'Merry Christmas♪ The present is... me♪' }, skillDesc: { ja: '空色ピースと紫ピースをランダムに最大5個ずつ\n赤ピースと緑ピースに変換します。', ko: '무작위 하늘 피스와 보라 피스를 최대 5개까지\n빨강 피스와 초록 피스로 바꿉니다.', en: 'Randomly changes up to 5 sky and purple pieces to red and green pieces.' } },
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/G8bR3lCakAEllOs?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G8bR3lCakAEllOs?format=jpg&name=large', attribute: 'purple', theme: { ja: '恋するサンタ', ko: '사랑에 빠진 산타', en: 'Santa in Love' }, skillName: { ja: 'プ、プレゼントは私…な、なんでもないわよ！', ko: '서, 선물은 나... 아, 아무것도 아니야!', en: 'T-the present is me... N-never mind!' }, skillDesc: { ja: '黄色ピースと赤ピースをランダムに最大5個ずつ\n緑ピースと紫ピースに変換します。', ko: '무작위 하늘 피스와 보라 피스를 최대 5개까지\n초록 피스와 보라 피스로 바꿉니다.', en: 'Randomly changes up to 5 yellow and red pieces to green and purple pieces.' } },
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/G7I4cSiacAASi2R?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G7I4cSiacAASi2R?format=jpg&name=large', attribute: 'green', theme: { ja: '恋するサンタ', ko: '사랑에 빠진 산타', en: 'Santa in Love' }, skillName: { ja: '"ハッピークリスマス"「ってやつだ」', ko: '"해피 크리스마스" 「라는 것이다」', en: '"Happy Christmas," "as they say."' }, skillDesc: { ja: '空色ピースと紫ピースをランダムに最大5個ずつ\n赤ピースと緑ピースに変換します。', ko: '무작위 하늘 피스와 보라 피스를 최대 5개까지\n빨강 피스와 초록 피스로 바꿉니다.', en: 'Randomly changes up to 5 sky and purple pieces to red and green pieces.'} },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/G7JGW0YbwAAHYLn?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G7JGW0YbwAAHYLn?format=jpg&name=large', attribute: 'red', theme: { ja: '恋するサンタ', ko: '사랑에 빠진 산타', en: 'Santa in Love' }, skillName: { ja: '一晩で配るためには最効率のルートを探す必要がある', ko: '하룻밤에 배달하기 위해서는 최고 효율의 루트를 찾을 필요가 있어', en: 'To deliver them in one night, we must find the most efficient route.' }, skillDesc: { ja: '紫ピースと空色ピースをランダムに最大5個ずつ\n緑ピースと赤ピースに変換します。', ko: '무작위 보라 피스와 하늘 피스를 최대 5개까지\n초록 피스와 빨강 피스로 바꿉니다.', en: 'Randomly changes up to 5 purple and sky pieces to green and red pieces.'} },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/G8bfunuakAcJOer?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G8bfunuakAcJOer?format=jpg&name=large', attribute: 'yellow', theme: { ja: '恋するサンタ', ko: '사랑에 빠진 산타', en: 'Santa in Love' }, skillName: { ja: '楠莉もプレゼントほしいのだ～！ひとつもらっちゃだめなのだー？', ko: '쿠스리도 선물이 갖고 싶은 것이다~! 하나 받으면 안 되는 것이다-?', en: 'Kusuri wants a present too~ yep yep!\nCan\'t I have just one, yep yep?' }, skillDesc: { ja: '緑ピースと赤ピースをランダムに最大5個ずつ\n空色ピースと黄色ピースに変換します。', ko: '무작위 초록 피스와 빨강 피스를 최대 5개까지\n하늘 피스와 노랑 피스로 바꿉니다.', en: 'Randomly changes up to 5 green and red pieces to sky and yellow pieces.'} },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/G7yS4M7aMAEjhX-?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G7yS4M7aMAEjhX-?format=jpg&name=large', attribute: 'yellow', theme: { ja: '恋するサンタ', ko: '사랑에 빠진 산타', en: 'Santa in Love' }, skillName: { ja: '薬以外の贈り物はあまり経験がなくてね', ko: '약 이외의 선물은 별로 경험이 없어서 말이야', en: 'I don\'t have much experience with gifts other than drug' }, skillDesc: { ja: '緑ピースと赤ピースをランダムに最大5個ずつ\n空色ピースと黄色ピースに変換します。', ko: '무작위 초록 피스와 빨강 피스를 최대 5개까지\n하늘 피스와 노랑 피스로 바꿉니다.', en: 'Randomly changes up to 5 green and red pieces to sky and yellow pieces.'} },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/G7JT8DvbgAMIQah?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G7JT8DvbgAMIQah?format=jpg&name=large', attribute: 'sky', theme: { ja: '恋するサンタ', ko: '사랑에 빠진 산타', en: 'Santa in Love' }, skillName: { ja: 'みんなにプレゼント持って来たわよ～！', ko: '모두에게 선물을 가져왔어~!', en: 'I brought presents for everyone~!' }, skillDesc: { ja: '赤ピースと緑ピースをランダムに最大5個ずつ\n空色ピースと空色ピースに変換します。', ko: '무작위 빨강 피스와 초록 피스를 최대 5개까지\n노랑 피스와 하늘 피스로 바꿉니다.', en: 'Randomly changes up to 5 red and green pieces to yellow and sky pieces.' } },

    // 새해 (4)
    { ...CHARS.karane, image: 'https://pbs.twimg.com/media/G9oGRSPaMAcAegA?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G9oGRSPaMAcAegA?format=jpg&name=large', attribute: 'sky', theme: { ja: 'お正月', ko: '새해', en: 'New Year' }, skillName: { ja: '今年も、よ、よろしく...なんて思ってないんだからね!!', ko: '올해도, 자, 잘 부탁... 한다든가 생각하지 않았거든!!', en: 'I\’m not thinking, "L-look forward to this year too," or anything!!' }, skillDesc: { ja: '「午」の形にピースを消します。', ko: '「午」 모양으로 피스를 제거합니다.', en: 'Clears pieces in a \'午\' (Horse) pattern (a cross with a top extension).' } },
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/G9oUGTKaoAE2LHk?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G9oUGTKaoAE2LHk?format=jpg&name=large', attribute: 'yellow', theme: { ja: 'お正月', ko: '새해', en: 'New Year' }, skillName: { ja: 'あけましておめでとうございます 末永くお願いしますね♡', ko: '새해 복 많이 받으세요 앞으로도 오래오래 잘 부탁드려요♡', en: 'Happy New Year. I look forward to being with you for a long time♡' }, skillDesc: { ja: '2ターンの間、3コンボ以上のコンボ倍率が2.5倍に変化します。', ko: '2턴 동안 3콤보 이상 콤보 배율이 2.5배가 됩니다.', en: 'For 2 turns, combo multiplier for 3+ combos becomes 2.5x.' } },
    { ...CHARS.hahari, image: 'https://pbs.twimg.com/media/G-WckHqa8AAtY6v?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G-WckHqa8AAtY6v?format=jpg&name=large', attribute: 'purple', theme: { ja: 'お正月', ko: '새해', en: 'New Year' }, skillName: { ja: 'あけましておめでとう♡今年もよろしくね♡', ko: '새해 복 많이 받아♡ 올해도 잘 부탁해♡', en: 'Happy New Year♡ Hope we have a great year together♡' }, skillDesc: { ja: '2ターンの間、3コンボ以上のコンボ倍率が2.5倍に変化します。', ko: '2턴 동안 3콤보 이상 콤보 배율이 2.5배가 됩니다.', en: 'For 2 turns, combo multiplier for 3+ combos becomes 2.5x.' } },
    { ...CHARS.nano, image: 'https://pbs.twimg.com/media/G-WqTHYb0AAdO_-?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/G-WqTHYb0AAdO_-?format=jpg&name=large', attribute: 'green', theme: { ja: 'お正月', ko: '새해', en: 'New Year' }, skillName: { ja: 'あけましておめでとう\n今年もあなたとたくさん過ごしたい', ko: '새해 복 많이 받아. 올해도 너와 잔뜩 보내고 싶어', en: 'Happy New Year. I want to spend a lot of time with you this year' }, skillDesc: { ja: '自分を中心として5×5ピースを消します。その後、下から2行を消します。', ko: '자신을 중심으로 5x5 피스를 제거합니다. 그 뒤에 맨 아래 2행을 제거합니다.', en: 'Clears a 5x5 area centered on self, then clears the bottom 2 rows.'} },

    // 달콤한 한 때 (4)
    { ...CHARS.shizuka, image: 'https://pbs.twimg.com/media/HADBa4abEAIiAJ0?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/HADBa4abEAIiAJ0?format=jpg&name=large', attribute: 'red', theme: { ja: '甘いひととき', ko: '달콤한 한 때', en: 'Sweet Moment' }, skillName: { ja: '"ハッピークリスマス"「ってやつだ」', ko: '"달콤한 유혹을" 「선사하도록 하지」', en: '"Shall we not offer" "a sweet temptation?"' }, skillDesc: { ja: '「ハート」の形にピースを消します。', ko: '하트 모양으로 피스를 제거합니다.', en: 'Clears pieces in a heart shape.'} },
    { ...CHARS.kusuri18, image: 'https://pbs.twimg.com/media/HADPLX3bEAQUKEB?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/HADPLX3bEAQUKEB?format=jpg&name=large', attribute: 'red', theme: { ja: '甘いひととき', ko: '달콤한 한 때', en: 'Sweet Moment' }, skillName: { ja: '薬ではなく愛情が入った手作りチョコなのだよ', ko: '약이 아닌 애정이 들어간 수제 초콜릿인 것이야', en: 'This is a handmade chocolate filled with love, not drug' }, skillDesc: { ja: '自分を中心としてハート形にピースを消します。', ko: '자신을 중심으로 하트 모양으로 피스를 제거합니다.', en: 'Clears pieces in a heart shape centered on self.'} },
    { ...CHARS.hakari, image: 'https://pbs.twimg.com/media/HAm23X0aQAANJ8f?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/HAm23X0aQAANJ8f?format=jpg&name=large', attribute: 'purple', theme: { ja: '甘いひととき', ko: '달콤한 한 때', en: 'Sweet Moment' }, skillName: { ja: 'あの、これ、貰ってください！\n隠し味はたっぷりな愛情ですから♡', ko: '저기, 이거, 받아주세요! 비밀 조미료는 듬뿍 담긴 사랑이니까요♡', en: 'Um, please take this! The secret ingredient is plenty of love♡' }, skillDesc: { ja: '自分を中心としてハート形にピースを消します。', ko: '자신을 중심으로 하트 모양으로 피스를 제거합니다.', en: 'Clears pieces in a heart shape.' } },
    { ...CHARS.kusuri, image: 'https://pbs.twimg.com/media/HAnEjQpbIAASH3I?format=jpg&name=large', detailImage: 'https://pbs.twimg.com/media/HAnEjQpbIAASH3I?format=jpg&name=large', attribute: 'sky', theme: { ja: '甘いひととき', ko: '달콤한 한 때', en: 'Sweet Moment' }, skillName: { ja: '楠莉の特製薬～！...じゃなくてチョコを作ってきたのだ！', ko: '쿠스리의 특제약~! ...이 아니라 초콜릿을 만든 것이다!', en: 'I made Kusuri\'s special drug~! ...I mean, chocolate!' }, skillDesc: { ja: '「ハート」の形にピースを消します。', ko: '하트 모양으로 피스를 제거합니다.', en: 'Clears pieces in a heart shape centered on self.'} },
];
